---
- name: Reload nginx
  listen: Reload nginx
  ansible.builtin.command: nginx -t
  changed_when: false

- name: Reload nginx service
  listen: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
